<?php

/**
 * @file
 * Contains kinoprofile.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function kinoprofile_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the kinoprofile module.
    case 'help.page.kinoprofile':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function kinoprofile_theme() {
  $theme = [];
  $theme['kino_profile'] = [
    'render element' => 'elements',
    'file' => 'kino_profile.page.inc',
    'template' => 'kino_profile',
  ];
  $theme['kino_profile_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'kino_profile.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function kinoprofile_theme_suggestions_kino_profile(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#kino_profile'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'kino_profile__' . $sanitized_view_mode;
  $suggestions[] = 'kino_profile__' . $entity->bundle();
  $suggestions[] = 'kino_profile__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'kino_profile__' . $entity->id();
  $suggestions[] = 'kino_profile__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
